package ro.fortech.BidStore.domain;

import java.sql.Date;

public class Item {
	//common
	private int id; //autogenerated
	private String name; //step 2
	private int bestBidValue; //not in DB (table bidding
	private Date bidClosingDate; //step 2
	private int numberOfBids; // not in DB (table bidding)
	
	//item page
	private String category; //step 1
	private int initialPrice; //step 2
	private Date bidOpeningDate; //step 2
	private int status; // default 2
	private String winner; // owner username
	private boolean toSell; // not in DB, only frontend
	private int yourBid; // not in DB (table bidding)
	
	//bidding page
	private String photo; //step 2
	private String description; //step 2
	
	// private int owner - only in entity - foreign key to user/profile
	
	public Item() {
		
	}
	
	public Item(int id, String name, String photo, String description, int bestBidValue, Date bidClosingDate,
			int numberOfBids) {
		super();
		this.id = id;
		this.name = name;
		this.photo = photo;
		this.description = description;
		this.bestBidValue = bestBidValue;
		this.bidClosingDate = bidClosingDate;
		this.numberOfBids = numberOfBids;
		
		//temporary
		this.bidOpeningDate = this.bidClosingDate;
		this.category = "category";
		this.status = 2;
		this.winner = "the winner";
		if(this.id%2 == 1) this.toSell = false;
		else this.toSell = true;
		this.yourBid = 10;
	}

	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getPhoto() {
		return photo;
	}
	public void setPhoto(String photo) {
		this.photo = photo;
	}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	public int getBestBidValue() {
		return bestBidValue;
	}
	public void setBestBidValue(int bestBidValue) {
		this.bestBidValue = bestBidValue;
	}
	public Date getBidClosingDate() {
		return bidClosingDate;
	}
	public void setBidClosingDate(Date bidClosingDate) {
		this.bidClosingDate = bidClosingDate;
	}
	public int getNumberOfBids() {
		return numberOfBids;
	}
	public void setNumberOfBids(int numberOfBids) {
		this.numberOfBids = numberOfBids;
	}

	public String getCategory() {
		return category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public int getInitialPrice() {
		return initialPrice;
	}

	public void setInitialPrice(int initialPrice) {
		this.initialPrice = initialPrice;
	}

	public Date getBidOpeningDate() {
		return bidOpeningDate;
	}

	public void setBidOpeningDate(Date bidOpeningDate) {
		this.bidOpeningDate = bidOpeningDate;
	}

	public int getStatus() {
		return status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public String getWinner() {
		return winner;
	}

	public void setWinner(String winner) {
		this.winner = winner;
	}

	public boolean isToSell() {
		return toSell;
	}

	public void setToSell(boolean toSell) {
		this.toSell = toSell;
	}

	public int getYourBid() {
		return yourBid;
	}

	public void setYourBid(int yourBid) {
		this.yourBid = yourBid;
	}

	@Override
	public String toString() {
		return "Item [id=" + id + ", name=" + name + ", bestBidValue=" + bestBidValue + ", bidClosingDate="
				+ bidClosingDate + ", numberOfBids=" + numberOfBids + ", category=" + category + ", initialPrice="
				+ initialPrice + ", bidOpeningDate=" + bidOpeningDate + ", status=" + status + ", winner=" + winner
				+ ", toSell=" + toSell + ", yourBid=" + yourBid + ", photo=" + photo + ", description=" + description
				+ "]";
	}
	
}
